name: ep_cf_catch
description: A new Flutter application.

version: 1.0.1+2

#1.0.1+2 adjust layout

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0+2
  shared_preferences: ^0.5.2
  sqflite: ^1.1.5
  rxdart: ^0.22.0
  provider: ^2.0.1
  intl: ^0.15.8
  font_awesome_flutter: ^8.4.0
  vibrate: ^0.0.4
  uuid: ^2.0.1
  google_sign_in: ^4.0.1+3
  flutter_auth_buttons: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

