name: ep_cf_catch
description: A new Flutter application.

version: 1.1.2+8

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0+2
  shared_preferences: ^0.5.2
  sqflite: ^1.1.5
  rxdart: ^0.22.0
  provider: ^2.0.1
  intl: ^0.15.8
  font_awesome_flutter: ^8.4.0
  vibration: 1.2.2
  uuid: ^2.0.1
  google_sign_in: ^4.0.1+3
  flutter_auth_buttons: ^0.5.0
  package_info: ^0.4.0+3
  barcode_scan: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

#1.1.2+8 change global url
#1.1.1+7 prevent catching tab from refresh when switching
#1.1.0+6 add scan function
#1.0.4+5 debug print
#1.0.3+4 add age
#1.0.2+3 adjust layout2
#1.0.1+2 adjust layout